apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: {{ .Values.driverName | quote }}
  labels:
    {{- include "local-path-csi.labels" . | nindent 4 }}
spec:
  attachRequired: false
  podInfoOnMount: true
  storageCapacity: true
  volumeLifecycleModes:
    - Persistent
