apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  # Requires the external-snapshotter CRDs + snapshot-controller installed
  # csi-snapshotter sidecar also needs them.
resources:
- rbac.yaml
- configmap.yaml
- csidriver.yaml
- controller.yaml
- node.yaml
- node-windows.yaml
- storageclass.yaml
images:
- name: ghcr.io/appmana/local-path-csi
  newName: local-path-csi
  newTag: e2e
- name: ghcr.io/appmana/local-path-helper
  newName: local-path-helper
  newTag: e2e
